### ISSUE TITLE
add plot method

### ISSUE THREAD

**Issue by rabutler-usbr** [rabutler-usbr/knnstdisagg#2]
this will create diagnostic plots for the disaggregation

- [x] plot historical data as points
- [x] plot options:
    - [x] color of historical point
    - [x] units
    - [x] y-units
- [x] months as month.abb
- [x] title is sitename
- [x] `...`
- [x] monthly pdf
- [x] annual pdf
- [x] add in other annual stats
- [x] create different plots, use `which`. see `plot.lm`
- [x]  Add in show argument, so that if you don't want to enter through every site, you do not have to.
    - [x] interactive mode
    - [x] how to handle if not interactive
- [x] return `knnstplot` object
- [x] tests
- [x] ~`save_knnst_plot()`~ see #14 
- [x] ~plot all/select sites~ see #15 
- [x] ~annual stats can be computed on CY or WY~ see #16

**Comment by rabutler-usbr** [comment]
see M:\Shared\CRSSinputProcessors\RPrograms\Disagg\code\plottingCode for existing code

**Comment by rabutler-usbr** [comment]
will need to add in the historical data to the `knnst` object, I think.

Otherwise, need to consider how to convert between intervening space and total space? That maybe is beyond the scope of this package?

**Comment by rabutler-usbr** [comment]
How do I capture all `...` parameters and appropriately pass them to the ggplot functions?
