### ISSUE TITLE
improve knn_space_time_disagg() tests and errors

### ISSUE THREAD

**Issue by rabutler-usbr** [rabutler-usbr/knnstdisagg#4]
- [x] need a test where there are no sf_sites, that works, to ensure that no warnings post anymore
    - handled in #24 
- [x] should error if index_years and k_weights are specified by user
    - fixed so message posts that k_weights is ignored if index_years is specified.
- [x] should check that multiple simulations work; also need to check that multiple
 simulations when specifying index_years works
    - handled already 
- [x] add test that checks that the monthly data for all gages sums to the annual data for the flow to disaggregate, but must check the appropriate gage.
    - test-space_time_disagg_simple.R included this for the most part. Added in 1 more test to make sure the data = the input data
- [x] add test where flows sum to index gage. The results should just be the input data if the input are volumes that exist in the index data when using k=1.
- [x] check that the `ofolder` exists and return better error if it doesn't
- [x] ~still need to make function much safer to the format of incoming data, i.e., which input need years associated with them, and which don't, matrices, vs. vectors, etc.~ #21
- [x] ~future enhancement: use rownames for mon_flow so that we can check that it contains the same years of data as the ann_index_flow. Also consider putting the years in the rownames of that variable, and (`x`), for consistency~ #11
- [x] ~should check that the mon_flow is either specified on water year vs. cy, or somehow check that~ #11
    - not sure if I can; might be up to the user
- [x] ~Should also consider round to nearest AF, but what are the effects of that on
matching the inut Lees Ferry value~ #20
